### ISSUE TITLE
Guesses still able to submit after guesses run out and after correct answer achieved

### ISSUE THREAD

**Issue by j4mesli** [j4mesli/tybwardle.io#3]
Write functionality that:

1. HIDES ALL SUBMISSIONS AFTER GUESSES RUN OUT / CORRECT GUESS
2. restricts submission and displays an apologetic message after all guesses used
3. restricts submission and displays a congratulatory message after a correct guess

**Comment by Babadinho** [comment]
Hello, I can fix this.

**Comment by j4mesli** [comment]
> Hello, I can fix this.

Hello! While I greatly appreciate the offer, this project is an educational experience for me, as I'm attempting to learn more about vanilla JS with it, so I'm afraid I'll have to turn down your offer. Thank you for your offer, but I can do this! :D

**Comment by Babadinho** [comment]
Okay. You can do this! Good luck.

**Comment by j4mesli** [comment]
> Okay. You can do this! Good luck.

Thank you so much! 😁

**Comment by j4mesli** [comment]
Functionality for hidden submissions, duplicate submission checking, apologetic, and congratulatory messages after guesses are all implemented. Game is now fully functional, but very ugly.

**Comment by Babadinho** [comment]
Good work. I suggest you read up on CSS Grid and Flexbox for better and responsive display of elements.
